#!/usr/bin/env python3
import argparse
import os
import subprocess
from pathlib import Path

HERE = os.path.abspath(os.path.dirname(__file__))


def build(package_directory, signing_key):
    cmd = ['debuild', '-S', '-k' + signing_key]

    env_copy = os.environ.copy()
    env_copy['DEBUILD_DPKG_BUILDPACKAGE_OPTS'] = '"--passphrase-file {} --batch --no-tty --no-use-agent"'.format(
        Path(HERE, 'gpg-passphrase').as_posix()
    )

    subprocess.Popen(cmd, cwd=Path(HERE, package_directory).as_posix(), env=env_copy).wait()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('package_directory')
    parser.add_argument('signing_key')
    args = parser.parse_args()

    package_directory = args.package_directory
    signing_key = args.signing_key

    build(package_directory, signing_key)

if __name__ == '__main__':
    main()
