#!/usr/bin/env python

from __future__ import print_function

import argparse
from launchpadlib.credentials import Credentials
from lazr.restfulclient.errors import HTTPError

def textangle(text, border_char='#'):
    rect_width = len(text) + 4
    print()
    print(border_char * rect_width)
    print('{} {} {}'.format(border_char, text, border_char))
    print(border_char * rect_width)
    print()


def get_launchpad_credentials_interactively(app_name, env):
    credentials = Credentials(app_name)
    request_token_info = credentials.get_request_token(web_root=env)

    textangle('Authorize {}'.format(app_name))
    print(request_token_info)

    complete = False
    while not complete:
        try:
            credentials.exchange_request_token_for_access_token(web_root=env)
            complete = True
        except HTTPError:
            pass

    creds = credentials.serialize().strip()
    textangle('Credentials for {}'.format(app_name))

    print(creds)

    textangle('Credential usage')
    print(
"""
    text_credentials = \"\"\"{}\"\"\"

    import launchpadlib
    from launchpadlib.credentials import Credentials
    credentials = launchpadlib.credentials.Credentials.from_string(text_credentials)

    from launchpadlib.launchpad import Launchpad
    launchpad = Launchpad(credentials, None, '/tmp/launchpad-cache-dir', service_root="{}")
    print(launchpad.me)

""".format(creds, env))


if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('app_name', help='The name of the app that you want to use Lauchpad with.')
    parser.add_argument('--env', default='production', help="Default: 'prodution'. Can also be 'staging'.")
    args = parser.parse_args()

    app_name = args.app_name
    env = args.env

    get_launchpad_credentials_interactively(app_name, env)
