#!/bin/bash

REPO="jetbrains-ppa"
DISTS=("bionic" "artful" "xenial" "trusty")
S3_BUCKET="s3:jetbrains-ppa:"

# The labels for the selection of packages you wish to have available.
# This is often a distinction provided by the repository maintainer to express something about the reliability or
# licensing restrictions of the software it contains.
COMP="main"

# https://keybase.io/jonasgroeger
GPG_KEY_ID="CCA0C0C4EA16B4EEA2D5720ABECD4B5B330D89B5"

# Create repo
aptly repo create -config=aptly.conf -component="${COMP}" "${REPO}"

# Add *.deb files
aptly repo add -config=aptly.conf "${REPO}" deb

# Publish repo to ~/.aptly/public
for DIST in ${DISTS[@]}; do
    aptly publish repo -config=aptly.conf -gpg-key="${GPG_KEY_ID}" -distribution="${DIST}" "${REPO}" "${S3_BUCKET}"
done

aptly publish list
