#!/bin/bash
set -euxo pipefail

REPO="jetbrains-ppa"
ARCH="amd64,i386"
S3_BUCKET="s3:jetbrains-ppa:"

# The labels for the selection of packages you wish to have available.
# This is often a distinction provided by the repository maintainer to express something about the reliability or
# licensing restrictions of the software it contains.
COMP="main"

GPG_KEY_ID="C647DF711B0CCC6A9F8769D0F3A767B5A6E8698A"

# Create repo
aptly -config=aptly.conf repo create -architectures="${ARCH}" -component="${COMP}" "${REPO}"

# Add *.deb files
aptly -config=aptly.conf repo add "${REPO}" deb

# Publish repo
aptly -config=aptly.conf publish repo -gpg-key="${GPG_KEY_ID}" -distribution=any -architectures="${ARCH}" "${REPO}" "${S3_BUCKET}"

aptly -config=aptly.conf publish list
