#!/usr/bin/env bash

export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get upgrade
apt-get install --yes --no-install-recommends \
    aptly curl binutils git gnupg2 jq ruby sed

gem install fpm
